steps:
  # 1. Build using the dynamic Build ID
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/project-ee16ab9f-709f-4851-b92/cloud-handson-v2/my-app:$BUILD_ID', '.']

  # 2. Push it to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/project-ee16ab9f-709f-4851-b92/cloud-handson-v2/my-app:$BUILD_ID']

  # 3. SSH into the VM, pull the new tag, stop the old container, and run the new one
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh bu-hands-on \
          --zone=us-central1-a \
          --tunnel-through-iap \
          --command="
            gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
            docker pull us-central1-docker.pkg.dev/project-ee16ab9f-709f-4851-b92/cloud-handson-v2/my-app:$BUILD_ID
            docker stop my-running-app || true
            docker rm my-running-app || true
            docker run -d --name my-running-app -p 80:80 us-central1-docker.pkg.dev/project-ee16ab9f-709f-4851-b92/cloud-handson-v2/my-app:$BUILD_ID
          "
images:
  - 'us-central1-docker.pkg.dev/project-ee16ab9f-709f-4851-b92/cloud-handson-v2/my-app:$BUILD_ID'

options:
  logging: CLOUD_LOGGING_ONLY
