steps:
  # 1. Build using a static tag (:v1) instead of $BUILD_ID
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/project-ee16ab9f-709f-4851-b92/cloud-handson/my-app:v1', '.']

  # 2. Push it over the old one
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/project-ee16ab9f-709f-4851-b92/cloud-handson/my-app:v1']

  # 3. No pulling required! Just reset the VM so it auto-refreshes
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['compute', 'instances', 'reset', 'bu-hands-on', '--zone=us-central1-a']

images:
  - 'us-central1-docker.pkg.dev/project-ee16ab9f-709f-4851-b92/cloud-handson/my-app:v1'

options:
  logging: CLOUD_LOGGING_ONLY
